---
title: "Exploraci贸n"
author: "Jacinto Carrasco Castillo"
date: "23 de marzo de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Cargamos los datos antes de ser preprocesados (datos y particiones)
load("Data/Basic.RData")

# Cargamos las funciones 
source("Functions-Preprocesamiento.R")
source("Functions-Models.R")
source("Functions-Cross-validation.R")

# Cargamos las bibliotecas necesarias
require(dplyr)
require(mice)
```


```{r}
data.tra <- data.tra %>%
   select(-CARRETERA) %>%
   transform(MES = month.names.2.numeric[MES],
             HORA = round(as.numeric(levels(HORA)[HORA])) %% 24,
             DIASEMANA = week.names.2.numeric[DIASEMANA])
```


# Distribuci贸n de los valores perdidos

```{r}
apply(data.tra, 2, function(x) mean(is.na(x)))
```

```{r}
plot(data.tra$ACOND_CALZADA ~ data.tra$TIPO_ACCIDENTE)
```

```{r}
data.tra.oth <- transform(data.tra,
                          ACOND_CALZADA = as.factor(ifelse(is.na(ACOND_CALZADA), "OTRO TIPO", 
                                                 levels(ACOND_CALZADA)[ACOND_CALZADA])),
                          PRIORIDAD = as.factor(ifelse(is.na(PRIORIDAD), "NINGUNA (SOLO NORMA)", 
                                             levels(PRIORIDAD)[PRIORIDAD])),
                          VISIBILIDAD_RESTRINGIDA = as.factor(ifelse(is.na(VISIBILIDAD_RESTRINGIDA), "OTRA_CAUSA", 
                                             levels(VISIBILIDAD_RESTRINGIDA)[VISIBILIDAD_RESTRINGIDA])),
                          OTRA_CIRCUNSTANCIA = as.factor(ifelse(is.na(OTRA_CIRCUNSTANCIA), "OTRA", 
                                                      levels(OTRA_CIRCUNSTANCIA)[OTRA_CIRCUNSTANCIA])),
                          MEDIDAS_ESPECIALES = as.factor(ifelse(is.na(MEDIDAS_ESPECIALES), "OTRA MEDIDA", 
                                                      levels(MEDIDAS_ESPECIALES)[MEDIDAS_ESPECIALES])),
                          ACERAS = as.factor(ifelse(is.na(ACERAS) & TIPO_VIA == "AUTOVIA",
                                          "NO HAY ACERA",
                                          levels(ACERAS)[ACERAS])))
```
                              

```{r}
data.tra.oth <- data.tra.oth %>%
   convertFactorIntoNumeric(c(5:7,13:28)) %>%
   transform(TIPO_ACCIDENTE = as.numeric(TIPO_ACCIDENTE) - 1)
```

                        
                              
```{r}
tipo.carr <- data.tra$TIPO_VIA
acond.calz <- data.tra$ACOND_CALZADA
plot(tipo.carr)

carr.calz <- select(data.tra, ACOND_CALZADA, TIPO_VIA)
levels(carr.calz$ACOND_CALZADA) <- c("C","N","O","P","R","I")
carr.calz <- transform(carr.calz, 
                       ACOND_CALZADA = as.factor(ifelse(is.na(ACOND_CALZADA), "NA", ACOND_CALZADA)))


``` 
 
 
 
```{r}
sapply(levels(data.tra$TIPO_VIA),
       function(l) mean(is.na(select(filter(data.tra,
                                            TIPO_VIA == l),
                                     ACERAS))))
```

```{r}
results <- cross.validation(data   = select(data.tra.oth, -TIPO_ACCIDENTE),
                            labels = data.tra.oth$TIPO_ACCIDENTE,
                            model.function = model.xgb,
                            folds = folds,
                            params = expand.grid(nrounds = 75))

```
```{r}
data.tst.oth <- data.tst %>%
   select(-CARRETERA) %>%
   transform(MES = month.names.2.numeric[MES],
             HORA = round(as.numeric(levels(HORA)[HORA])) %% 24,
             DIASEMANA = week.names.2.numeric[DIASEMANA])%>%
   transform(ACOND_CALZADA = as.factor(ifelse(is.na(ACOND_CALZADA), "OTRO TIPO", 
                                              levels(ACOND_CALZADA)[ACOND_CALZADA])),
             PRIORIDAD = as.factor(ifelse(is.na(PRIORIDAD), "NINGUNA (SOLO NORMA)", 
                                          levels(PRIORIDAD)[PRIORIDAD])),
             VISIBILIDAD_RESTRINGIDA = as.factor(ifelse(is.na(VISIBILIDAD_RESTRINGIDA), "OTRA_CAUSA", 
                                                        levels(VISIBILIDAD_RESTRINGIDA)[VISIBILIDAD_RESTRINGIDA])),
             OTRA_CIRCUNSTANCIA = as.factor(ifelse(is.na(OTRA_CIRCUNSTANCIA), "OTRA", 
                                                   levels(OTRA_CIRCUNSTANCIA)[OTRA_CIRCUNSTANCIA])),
             MEDIDAS_ESPECIALES = as.factor(ifelse(is.na(MEDIDAS_ESPECIALES), "OTRA MEDIDA", 
                                                   levels(MEDIDAS_ESPECIALES)[MEDIDAS_ESPECIALES])),
             ACERAS = as.factor(ifelse(is.na(ACERAS) & TIPO_VIA == "AUTOVIA",
                                       "NO HAY ACERA",
                                       levels(ACERAS)[ACERAS]))) %>%
   convertFactorIntoNumeric(c(5:7,13:28))
```

```{r}

#' Generaci贸n del modelo con los datos de entrenamiento
set.seed(3141592)
model <- model.xgb(select(data.tra.oth, -TIPO_ACCIDENTE),
                   data.tra.oth$TIPO_ACCIDENTE,
                   params = c(nrounds = 75))

#' Predicci贸n sobre datos de test
#' Escritura de los datos
predictions <- predict(model, as.matrix(data.tst.oth))
writePredictions(predictions, "predictions.imp.others")
```

